// export * from "./loader";
export * from "./promised";
export * from "./responsive";
export * from "./removeAcents";
export * from "./getUrlPublic";
export * from "./isType";
export * from "./searchify";
export * from "./getNameId";
export * from "./localStorage";
export * from "./acl";
